
theme = "tokyonight"

[editor]
line-number = "relative"
scroll-lines = 1
scrolloff = 12
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

#[[language]]
#name = "rust"

#[language.language-server]
#command = "rustup"
#args = ["run", "stable", "rust-analyzer"]

#[language.config.check]
#command = "clippy"
