# ~/.zshrc

#Aliases
set_alias() {
  cmd="$1"
  executable="$2"
  shift 2
  if command -v "$executable" >/dev/null 2>&1; then
    alias "$cmd"="$executable $*"
  else
    echo "$cmd: $executable not found"
  fi
}
set_alias vim nvim
set_alias cat bat
set_alias ls eza
set_alias la eza -la
set_alias grep rg
set_alias lg lazygit
alias brewup="brew update && brew upgrade && brew cleanup && brew doctor"

export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

source <(ng completion script) # Load Angular CLI autocompletion.

# Fuzzy finding config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Init zoxide
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
