# ~/.zshrc

#Aliases
set_alias() {
  cmd="$1"
  executable="$2"
  shift 2
  if command -v "$executable" >/dev/null 2>&1; then
    alias "$cmd"="$executable $*"
  else
    echo "$cmd: $executable not found"
  fi
}
set_alias vim nvim
set_alias cat bat
set_alias ls exa
set_alias la exa -la
set_alias grep rg
set_alias lg lazygit

# Fuzzy finding config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export TERM=tmux-256color

eval "$(starship init zsh)"
